services:
  edusoft-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edusoft_question_generator
    restart: unless-stopped
    ports:
      - "8002:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
    volumes:
      - .:/app